from ._armature_def import (
    _UR10E_BASE_ROT_R,
    _UR10E_R_Y_90,
    _UR10E_ARMATURE_D1,
    _UR10E_ARMATURE_SHOULDER_OFFSET,
    _UR10E_ARMATURE_A2,
    _UR10E_ARMATURE_ELBOW_OFFSET,
    _UR10E_ARMATURE_A3,
    _UR10E_ARMATURE_D4,
    _UR10E_ARMATURE_D5,
    _UR10E_ARMATURE_EE_OFFSET
)
