controller_list:
  - name: joint_state_controller
    type: joint_state_controller/JointStateController
    joints: []

  - name: pos_joint_traj_controller
    type: position_controllers/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  - name: hande_gripper_controller
    type: effort_controllers/JointTrajectoryController
    joints:
      - hande_left_finger_joint

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.01
  state_publish_rate: 50
  action_monitor_rate: 20

hande_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - hande_left_finger_joint
  gains:
    hande_left_finger_joint: {p: 5.0, i: 0.01, d: 0.1}
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.01
    hande_left_finger_joint: {trajectory: 0.02, goal: 0.01}
  state_publish_rate: 50
  action_monitor_rate: 20
