controller_list:
  - name: joint_state_controller
    type: joint_state_controller/JointStateController
    joints: []

  - name: eff_joint_traj_controller
    type: effort_controllers/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  - name: hande_gripper_controller
    type: effort_controllers/JointTrajectoryController
    joints:
      - hande_left_finger_joint

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

eff_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10.0}
    shoulder_lift_joint: {p: 100.0, i: 0.01, d: 10.0}
    elbow_joint: {p: 100.0, i: 0.01, d: 10.0}
    wrist_1_joint: {p: 50.0, i: 0.01, d: 5.0}
    wrist_2_joint: {p: 50.0, i: 0.01, d: 5.0}
    wrist_3_joint: {p: 20.0, i: 0.01, d: 1.0}
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.01
  state_publish_rate: 50
  action_monitor_rate: 20

hande_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - hande_left_finger_joint
  gains:
    hande_left_finger_joint: {p: 5.0, i: 0.01, d: 0.1}
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.01
    hande_left_finger_joint: {trajectory: 0.02, goal: 0.01}
  state_publish_rate: 50
  action_monitor_rate: 20
