controller_list:
  - name: hande_gripper_controller
    type: effort_controllers/JointTrajectoryController
    joints:
      - hande_left_finger_joint

hande_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - hande_left_finger_joint
  gains:
    hande_left_finger_joint: { p: 5.0, i: 0.01, d: 0.1 }
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.01
    hande_left_finger_joint: {trajectory: 0.02, goal: 0.01}
  state_publish_rate: 50
  action_monitor_rate: 20
