controller_list:
  - name: joint_state_controller
    type: joint_state_controller/JointStateController
    joints: [ ]

  - name: pos_joint_traj_controller
    type: position_controllers/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  - name: hande_gripper_controller
    type: position_controllers/GripperActionController
    joints:
      - hande_left_finger_joint

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

hande_gripper_controller:
  type: position_controllers/GripperActionController
  joint: hande_left_finger_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0

gazebo_ros_control:
  pid_gains:
    shoulder_pan_joint:       {p: 15.0, i: 0.0, d: 10.0}
    shoulder_lift_joint:      {p: 15.0, i: 0.0, d: 10.0}
    elbow_joint:              {p: 15.0, i: 0.0, d: 10.0}
    wrist_1_joint:            {p: 5.0, i: 0.0, d: 5.0}
    wrist_2_joint:            {p: 5.0, i: 0.0, d: 5.0}
    wrist_3_joint:            {p: 5.0, i: 0.0, d: 5.0}
    hande_left_finger_joint:  {p: 2.0,  i: 0.001, d: 5.0}